import { afterEach, describe, expect, it } from "vitest";
import {
  generateAutoToken,
  isDevEnvironment,
  isLoopbackAddress,
  resolveMcpAuth,
} from "../src/mcp/autoToken.js";
import { makeConfig } from "./helpers.js";

describe("generateAutoToken", () => {
  it("returns 64 lowercase hex characters", () => {
    expect(generateAutoToken()).toMatch(/^[0-9a-f]{64}$/);
  });

  it("returns a different token on every call", () => {
    expect(generateAutoToken()).not.toBe(generateAutoToken());
  });
});

describe("isLoopbackAddress", () => {
  it("accepts the IPv4 loopback range 127.0.0.0/8", () => {
    expect(isLoopbackAddress("127.0.0.1")).toBe(true);
    expect(isLoopbackAddress("127.0.0.0")).toBe(true);
    expect(isLoopbackAddress("127.255.255.255")).toBe(true);
    expect(isLoopbackAddress("127.1.2.3")).toBe(true);
  });

  it("accepts the IPv6 loopback address", () => {
    expect(isLoopbackAddress("::1")).toBe(true);
  });

  it("accepts IPv4-mapped IPv6 loopback addresses", () => {
    expect(isLoopbackAddress("::ffff:127.0.0.1")).toBe(true);
  });

  it("rejects non-loopback IPv4 addresses, including IPv4-mapped ones", () => {
    expect(isLoopbackAddress("10.0.0.5")).toBe(false);
    expect(isLoopbackAddress("192.168.1.1")).toBe(false);
    expect(isLoopbackAddress("8.8.8.8")).toBe(false);
    expect(isLoopbackAddress("::ffff:10.0.0.1")).toBe(false);
  });

  it("rejects non-loopback IPv6 addresses", () => {
    expect(isLoopbackAddress("2001:db8::1")).toBe(false);
    expect(isLoopbackAddress("fe80::1")).toBe(false);
  });

  it("rejects missing/empty/malformed input", () => {
    expect(isLoopbackAddress(undefined)).toBe(false);
    expect(isLoopbackAddress(null)).toBe(false);
    expect(isLoopbackAddress("")).toBe(false);
    expect(isLoopbackAddress("not-an-ip")).toBe(false);
    expect(isLoopbackAddress("127.0.0.1x")).toBe(false);
  });
});

describe("isDevEnvironment", () => {
  const originalNodeEnv = process.env.NODE_ENV;

  afterEach(() => {
    process.env.NODE_ENV = originalNodeEnv;
  });

  it("is true when NODE_ENV is unset, 'test', 'development', or anything else non-production", () => {
    for (const value of [undefined, "test", "development", "staging"]) {
      if (value === undefined) delete process.env.NODE_ENV;
      else process.env.NODE_ENV = value;
      expect(isDevEnvironment()).toBe(true);
    }
  });

  it("is false only when NODE_ENV is exactly 'production'", () => {
    process.env.NODE_ENV = "production";
    expect(isDevEnvironment()).toBe(false);
  });
});

describe("resolveMcpAuth", () => {
  it("uses the explicit token and marks it not auto-generated when MCP_AUTH_TOKEN is set", async () => {
    const state = await resolveMcpAuth(makeConfig({ MCP_AUTH_TOKEN: "a-very-secret-token!" }));
    expect(state).toEqual({ token: "a-very-secret-token!", autoGenerated: false, enabled: true });
  });

  it("uses the explicit token even in production", async () => {
    const originalNodeEnv = process.env.NODE_ENV;
    process.env.NODE_ENV = "production";
    try {
      const state = await resolveMcpAuth(makeConfig({ MCP_AUTH_TOKEN: "a-very-secret-token!" }));
      expect(state).toEqual({ token: "a-very-secret-token!", autoGenerated: false, enabled: true });
    } finally {
      process.env.NODE_ENV = originalNodeEnv;
    }
  });

  it("generates a token and marks it auto-generated + enabled when MCP_AUTH_TOKEN is unset in a dev environment", async () => {
    const state = await resolveMcpAuth(makeConfig({ MCP_AUTH_TOKEN: undefined }));
    expect(state.autoGenerated).toBe(true);
    expect(state.enabled).toBe(true);
    expect(state.token).toMatch(/^[0-9a-f]{64}$/);
  });

  // Finding: production deployments that deliberately left MCP_AUTH_TOKEN
  // unset previously got a hard 503 across the whole /api/mcp* surface.
  // Auto-token mode must not silently turn that into a live (if
  // loopback-gated) surface in production — the loopback gate itself
  // doesn't hold behind a same-host reverse proxy, so production needs the
  // old "off" behavior, not a network-level gate.
  it("does not auto-generate a token in production when MCP_AUTH_TOKEN is unset -- returns disabled instead", async () => {
    const originalNodeEnv = process.env.NODE_ENV;
    process.env.NODE_ENV = "production";
    try {
      const state = await resolveMcpAuth(makeConfig({ MCP_AUTH_TOKEN: undefined }));
      expect(state).toEqual({ token: null, autoGenerated: false, enabled: false });
    } finally {
      process.env.NODE_ENV = originalNodeEnv;
    }
  });

  it("does not attempt to reuse a handshake-file token unless reuseFromHandshake is passed", async () => {
    // No filesystem access at all in this path -- reuseFromHandshake
    // defaults to false, so a plain resolveMcpAuth(config) call (what every
    // non-dev-server buildApp() caller does) never even looks at
    // ~/.pen-editor/mcp.json.
    const state = await resolveMcpAuth(makeConfig({ MCP_AUTH_TOKEN: undefined }));
    expect(state.autoGenerated).toBe(true);
    expect(state.token).toMatch(/^[0-9a-f]{64}$/);
  });
});
