-- Public canvas sharing: one row per share link. `id` doubles as the public
-- URL slug (short, url-safe, generated by the route — not a UUID, since it
-- also has to be short enough to paste comfortably) and `edit_token` is a
-- separate, longer secret the sharer's own browser holds onto so it can
-- update or unshare later without any real auth — same anonymous trust
-- model as `agent_memory`/`user_skills` (`owner_id` is the anonymous
-- `pen.userId`, shape-checked only, never authenticated). The public GET
-- route never returns `edit_token`; every mutating route matches it in the
-- SQL WHERE clause, never in application code, so the secret never has to
-- round-trip through a comparison that could leak via timing or a stray log
-- line.
--
-- `document` is TEXT, not JSONB, on purpose: the payload is an
-- already-serialized `PenDocument` JSON string that the browser must read
-- back byte-identical to what it sent. JSONB would not preserve it — it
-- reorders object keys, drops duplicate ones, and hard-errors on a `\u0000`
-- escape, which a text node's string content can legitimately carry. Nothing
-- server-side ever queries *into* this document either, so JSONB would buy
-- indexability we have no use for at the cost of fidelity we do need.
CREATE TABLE IF NOT EXISTS shared_canvases (
  id         TEXT PRIMARY KEY,          -- short url-safe id; the public link
  owner_id   TEXT NOT NULL,             -- anonymous pen.userId of the sharer
  edit_token TEXT NOT NULL,             -- secret required to update/unshare
  title      TEXT NOT NULL DEFAULT 'Untitled',
  document   TEXT NOT NULL,             -- serialized PenDocument JSON, verbatim
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Backs a future "your shared canvases" listing (newest-edited first, scoped
-- to one owner) — the same access shape `user_skills_user_updated_idx` and
-- `showcase_app_likes`-adjacent indexes in this file already serve for their
-- own per-owner tables.
CREATE INDEX IF NOT EXISTS shared_canvases_owner_updated_idx
  ON shared_canvases (owner_id, updated_at DESC);
