-- Organizations (Better Auth 1.7.7 `organization` plugin, Phase 8.1).
-- GENERATED by Better Auth's own planner (`getMigrations(auth.options)
-- .compileMigrations()`) against a database with 016_auth.sql applied, then
-- made idempotent (IF NOT EXISTS). Additive only: 016 is never edited.
-- Plugin config: custom roles owner / editor / viewer (src/auth/organization.ts).
-- Regenerate into a NEW numbered migration when the plugin set or the library
-- version changes; test/auth-migration.test.ts fails until the planner plans
-- nothing.

ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "activeOrganizationId" text;

CREATE TABLE IF NOT EXISTS "organization" ("id" text not null primary key, "name" text not null, "slug" text not null unique, "logo" text, "createdAt" timestamptz not null, "metadata" text);

CREATE TABLE IF NOT EXISTS "member" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "userId" text not null references "user" ("id") on delete cascade, "role" text not null, "createdAt" timestamptz not null);

CREATE TABLE IF NOT EXISTS "invitation" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "email" text not null, "role" text, "status" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "inviterId" text not null references "user" ("id") on delete cascade);

CREATE INDEX IF NOT EXISTS "member_organizationId_idx" ON "member" ("organizationId");

CREATE INDEX IF NOT EXISTS "member_userId_idx" ON "member" ("userId");

CREATE INDEX IF NOT EXISTS "invitation_organizationId_idx" ON "invitation" ("organizationId");

CREATE INDEX IF NOT EXISTS "invitation_email_idx" ON "invitation" ("email");
