import { randomBytes } from "node:crypto";
import { chmod, mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import type { Config } from "../config.js";

// Minimal logger shape so callers can pass a Fastify/pino logger without a
// hard dependency on its full type.
export interface WarnLogger {
  warn: (msg: string) => void;
  info?: (msg: string) => void;
}

// Whether MCP_AUTH_TOKEN was explicitly configured (remote/operator case,
// unchanged behavior) or generated/reused by us for local dev (auto case,
// gated to loopback callers only — see isLoopbackAddress). `enabled: false`
// means the whole /api/mcp* surface must 503, exactly like every deployment
// before auto-token mode existed: no explicit token, and no dev signal
// (see isDevEnvironment) to justify minting one.
export interface McpAuthState {
  token: string | null;
  autoGenerated: boolean;
  enabled: boolean;
}

export interface ResolveMcpAuthOptions {
  // Only the long-running dev server instance should read a possibly-stale
  // handshake file left by its own previous run and reuse its token (finding
  // 3) — a throwaway buildApp() call (tests, one-off scripts) has no
  // business doing this lookup at all. Mirrors BuildAppOptions.publishHandshake.
  reuseFromHandshake?: boolean;
}

// Dev signal gating auto-token mode. `HOST` is not a reliable signal here:
// the documented default dev config leaves HOST at "0.0.0.0" (config.ts), so
// requiring HOST to resolve to loopback would disable auto-token mode for
// the common case it exists to serve. NODE_ENV is the standard, explicit
// opt-in/opt-out signal for "this is a production deployment" and is what
// every deploy of this app already sets in production (unlike HOST, which
// dev and prod both often leave at their defaults) — so it's the one we key
// on. Anything other than exactly "production" is treated as dev.
export function isDevEnvironment(): boolean {
  return process.env.NODE_ENV !== "production";
}

export async function resolveMcpAuth(
  config: Config,
  options: ResolveMcpAuthOptions = {},
): Promise<McpAuthState> {
  if (config.MCP_AUTH_TOKEN) {
    return { token: config.MCP_AUTH_TOKEN, autoGenerated: false, enabled: true };
  }
  if (!isDevEnvironment()) {
    // Production with no explicit token: the exact pre-auto-token behavior —
    // the whole /api/mcp* surface stays off. Auto-generating and gating on
    // loopback is not a safe substitute here: behind a same-host reverse
    // proxy (nginx/caddy terminating on 127.0.0.1) every internet request
    // looks like loopback (see mcp/routes.ts checkLoopback), so the gate
    // would enforce nothing on exactly the deployments most likely to have
    // deliberately left MCP_AUTH_TOKEN unset to mean "off".
    return { token: null, autoGenerated: false, enabled: false };
  }
  const reused = options.reuseFromHandshake ? await readReusableToken(config.PORT) : undefined;
  return { token: reused ?? generateAutoToken(), autoGenerated: true, enabled: true };
}

export function generateAutoToken(): string {
  return randomBytes(32).toString("hex");
}

// A backend restart under `tsx watch` (or any routine dev restart) used to
// mint a fresh token every time, silently breaking every already-connected
// client: pen-editor's vite dev server reads the token once at boot and
// inlines it, so a new token 401s the open tab's WS reconnect loop until the
// frontend dev server is restarted too. Reuse the token already on disk when
// it looks like it belongs to the same dev server (same configured port,
// well-formed) instead. Returns undefined (mint a new one) on any mismatch,
// missing file, or parse error — never throws.
async function readReusableToken(expectedPort: number): Promise<string | undefined> {
  try {
    const raw = await readFile(getHandshakePath(), "utf8");
    const parsed = JSON.parse(raw) as Partial<HandshakeFileEntry>;
    if (
      typeof parsed.token === "string" &&
      /^[0-9a-f]{64}$/.test(parsed.token) &&
      typeof parsed.port === "number" &&
      parsed.port === expectedPort
    ) {
      return parsed.token;
    }
  } catch {
    // Missing/corrupt/unreadable file -> mint a new token below.
  }
  return undefined;
}

// True for 127.0.0.0/8, ::1, and IPv4-mapped ::ffff:127.x.x.x. Deliberately
// narrow — this backs a security boundary (see mcp/routes.ts), so anything
// not recognizably loopback is treated as remote.
export function isLoopbackAddress(address: string | null | undefined): boolean {
  if (!address) return false;
  if (address === "::1") return true;
  const v4 = address.startsWith("::ffff:") ? address.slice("::ffff:".length) : address;
  const parts = v4.split(".");
  if (parts.length !== 4) return false;
  // Every octet must be a plain base-10 integer 0-255 (no signs, no
  // whitespace, no trailing garbage like "1x") for this to count as a real
  // dotted-quad address at all.
  if (!parts.every((part) => /^\d{1,3}$/.test(part) && Number(part) <= 255)) return false;
  return Number(parts[0]) === 127;
}

export interface HandshakeFileEntry {
  url: string;
  token: string;
  port: number;
}

// Not memoized: reads homedir() fresh each call so tests can point it at a
// temp directory via `vi.mock("node:os", ...)` without needing a restart.
export function getHandshakeDir(): string {
  return join(homedir(), ".pen-editor");
}

export function getHandshakePath(): string {
  return join(getHandshakeDir(), "mcp.json");
}

// Writes the shared handshake file two other agents read to discover the
// local backend without any manual token wiring. Contract (do not deviate):
// `{ url: "http://127.0.0.1:<port>/api/mcp", token: "<64 lowercase hex>", port }`
// at `~/.pen-editor/mcp.json`, dir mode 0700, file mode 0600.
//
// Atomic: written to a temp file in the same directory, then renamed, so a
// concurrent reader never observes a partial write. Never throws — a
// read-only filesystem or missing homedir must not crash server startup;
// callers get a warning on the logger instead.
export async function writeHandshakeFile(
  entry: HandshakeFileEntry,
  log: WarnLogger,
): Promise<void> {
  const dir = getHandshakeDir();
  const target = getHandshakePath();
  try {
    await mkdir(dir, { recursive: true, mode: 0o700 });
    // mkdir's `mode` only applies when it creates the directory; chmod
    // explicitly so a pre-existing directory with looser permissions (or a
    // restrictive umask on creation) doesn't leave the token world-readable.
    await chmod(dir, 0o700);

    const tmpPath = join(dir, `.mcp.json.${process.pid}.${Date.now()}.tmp`);
    // Set mode explicitly rather than relying on umask.
    await writeFile(tmpPath, JSON.stringify(entry, null, 2) + "\n", { mode: 0o600 });
    await chmod(tmpPath, 0o600);
    await rename(tmpPath, target);
    log.info?.(`[mcp] wrote local handshake file to ${target}`);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    log.warn(`[mcp] failed to write handshake file at ${target}: ${message}`);
  }
}

// Best-effort cleanup on graceful shutdown. Only removes the file when it
// still holds the token/port this process itself wrote — otherwise a
// second, short-lived auto-token instance (a test run, a second checkout, a
// script calling buildApp) would delete the handshake file belonging to a
// still-running dev backend, and the editor/plugin would lose discovery. A
// stale file surviving a crash (this process's own, never overwritten by
// anyone else) is not otherwise a problem: it just points a reader at a
// token/port that no longer accepts connections, which surfaces as an
// ordinary connection error — not a security issue, since the loopback
// restriction and per-process token still apply to whatever backend (if
// any) is actually listening.
export async function removeHandshakeFile(
  entry: HandshakeFileEntry,
  log: WarnLogger,
): Promise<void> {
  const target = getHandshakePath();
  try {
    const raw = await readFile(target, "utf8");
    const parsed = JSON.parse(raw) as Partial<HandshakeFileEntry>;
    if (parsed.token !== entry.token || parsed.port !== entry.port) {
      log.info?.(
        `[mcp] handshake file at ${target} no longer belongs to this process — leaving it in place.`,
      );
      return;
    }
    await rm(target, { force: true });
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    if (code === "ENOENT") return; // already gone
    const message = err instanceof Error ? err.message : String(err);
    log.warn(`[mcp] failed to remove handshake file at ${target}: ${message}`);
  }
}
