import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import websocketPlugin, { type WebSocket } from "@fastify/websocket";
import { type Config } from "../config.js";
import { isCredentialedOrigin, setMcpCorsHeaders } from "../plugins/cors.js";
import { LEGACY_MCP_CONTEXT } from "./server.js";
import { serveStreamable } from "./streamable.js";
import { remoteMcpRoutes } from "./remoteRoutes.js";
import { registerSession, revalidateSession, type BridgeOwner, type SessionCredential } from "./bridge.js";
import { readSession } from "../auth/actor.js";
import type { AuthSession } from "../auth/index.js";
import { constantTimeEqual, extractBearerToken } from "./auth.js";
import { isLoopbackAddress, type McpAuthState } from "./autoToken.js";

const MCP_DISABLED_MESSAGE = "MCP is not enabled on this server (MCP_AUTH_TOKEN unset).";
const LOOPBACK_ONLY_MESSAGE =
  "MCP is using an auto-generated local-dev token and only accepts connections from 127.0.0.1. Set MCP_AUTH_TOKEN to allow remote access.";
const FORBIDDEN_ORIGIN = { status: 403, error: "Forbidden origin" } as const;
export const SESSION_REVALIDATE_INTERVAL_MS = 60_000;
const legacyDisabled = { status: 503, error: MCP_DISABLED_MESSAGE } as const;

export async function mcpRoutes(
  app: FastifyInstance,
  config: Config,
  mcpAuth: McpAuthState,
): Promise<void> {
  await app.register(websocketPlugin);

  const setCorsHeaders = (request: FastifyRequest, reply: FastifyReply): void =>
    setMcpCorsHeaders(config, request, reply);

  // In auto-token mode (MCP_AUTH_TOKEN unset — we generated one at startup)
  // the token alone isn't enough of a gate: it's sitting in a
  // world-readable-by-the-user handshake file and HOST defaults to
  // 0.0.0.0, so the port is reachable from the LAN. Restrict every request
  // to loopback callers in that mode; an explicitly configured token (the
  // remote/operator case) is unrestricted, exactly as before. Uses the raw
  // socket address only — never X-Forwarded-For, which a LAN caller could
  // set to anything.
  function checkLoopback(request: FastifyRequest, reply: FastifyReply): boolean {
    if (!mcpAuth.autoGenerated) return true;
    if (isLoopbackAddress(request.socket.remoteAddress)) return true;
    reply.status(403).send({ error: LOOPBACK_ONLY_MESSAGE });
    return false;
  }

  // Returns true and lets the caller proceed, or sends the error response
  // and returns false. `enabled: false` (no explicit token, no dev signal —
  // see resolveMcpAuth) -> 503, exactly the pre-auto-token behavior; missing
  // or wrong bearer token -> 401; non-loopback caller in auto-token mode ->
  // 403.
  function requireAuth(request: FastifyRequest, reply: FastifyReply): boolean {
    if (!mcpAuth.enabled || mcpAuth.token === null) {
      reply.status(503).send({ error: MCP_DISABLED_MESSAGE });
      return false;
    }
    if (!checkLoopback(request, reply)) return false;
    const token = extractBearerToken(request.headers.authorization);
    if (!token || !constantTimeEqual(token, mcpAuth.token)) {
      reply.status(401).send({ error: "Unauthorized" });
      return false;
    }
    return true;
  }

  app.options("/api/mcp", async (request, reply) => {
    setCorsHeaders(request, reply);
    reply.status(204).send();
  });

  async function handleStreamableRequest(
    request: FastifyRequest,
    reply: FastifyReply,
    body?: unknown,
  ): Promise<void> {
    setCorsHeaders(request, reply);
    if (!requireAuth(request, reply)) return;
    await serveStreamable(request, reply, LEGACY_MCP_CONTEXT, body);
  }

  app.post("/api/mcp", (request, reply) => handleStreamableRequest(request, reply, request.body));

  app.get("/api/mcp", (request, reply) => handleStreamableRequest(request, reply));

  app.delete("/api/mcp", async (request, reply) => {
    setCorsHeaders(request, reply);
    if (!requireAuth(request, reply)) return;
    // Stateless mode (sessionIdGenerator: undefined) has no server-side
    // session to delete.
    reply.status(204).send();
  });

  // The upgrade is authenticated in preValidation (before the handshake) and
  // the verdict handed to the socket handler through this map: a legacy
  // `?token=` makes an owner-null session, a session cookie an owner-user one.
  const wsOwners = new WeakMap<FastifyRequest, { owner: BridgeOwner; credential: SessionCredential | null }>();
  const unauthorized = { status: 401, error: "Unauthorized" } as const;

  // Cookie auth is the account path (needs auth on); the legacy token path is
  // unchanged, including its 503 / loopback 403 / 401 answers. With auth on,
  // a cookie-authenticated tab works even when MCP_AUTH_TOKEN is unset.
  async function authenticateUpgrade(
    request: FastifyRequest,
  ): Promise<{ owner: BridgeOwner; credential: SessionCredential | null } | { status: number; error: string }> {
    const query = request.query as { token?: string };
    if (!query.token) {
      // A browser attaches cookies to a cross-site WebSocket upgrade, so the
      // cookie path demands an Origin we trust with credentials (CSWSH).
      if (!request.headers.cookie) return mcpAuth.enabled || app.auth ? unauthorized : legacyDisabled;
      if (!isCredentialedOrigin(config, request.headers.origin)) return FORBIDDEN_ORIGIN;
      const session = await readSession(request, { fresh: true });
      if (session) return { owner: session.user.id, credential: cookieCredential(request, session) };
      return mcpAuth.enabled || app.auth ? unauthorized : legacyDisabled;
    }
    if (!mcpAuth.enabled || mcpAuth.token === null) return legacyDisabled;
    if (mcpAuth.autoGenerated && !isLoopbackAddress(request.socket.remoteAddress)) {
      return { status: 403, error: LOOPBACK_ONLY_MESSAGE };
    }
    if (!constantTimeEqual(query.token, mcpAuth.token)) return unauthorized;
    return { owner: null, credential: null };
  }

  // The one place a cookie tab's auth session is re-checked: a real DB lookup
  // (fresh = bypass the cookie cache) that must still find the SAME session.
  function cookieCredential(request: FastifyRequest, session: AuthSession): SessionCredential {
    return {
      expiresAt: new Date(session.session.expiresAt).getTime(),
      isValid: async () => {
        const current = await readSession(request, { fresh: true });
        return current?.session.id === session.session.id;
      },
    };
  }

  app.get(
    "/api/mcp/ws",
    {
      websocket: true,
      preValidation: (request, reply, done) => {
        void authenticateUpgrade(request)
          .then((verdict) => {
            if ("owner" in verdict) {
              wsOwners.set(request, verdict);
              done();
              return;
            }
            reply.status(verdict.status).send({ error: verdict.error });
            done(new Error(`mcp ws rejected (${verdict.status})`));
          })
          .catch((err: unknown) => done(err instanceof Error ? err : new Error(String(err))));
      },
    },
    (socket, request) => {
      // No recorded verdict must never mean "owner null" (the legacy
      // surface): refuse the socket instead.
      const verdict = wsOwners.get(request);
      if (!verdict) {
        socket.close(1008, "unauthenticated");
        return;
      }
      registerSession(socket, verdict.owner, verdict.credential);
      startKeepalive(socket);
      if (verdict.credential) startSessionRevalidation(socket);
    },
  );

  await remoteMcpRoutes(app, config);
}

export const KEEPALIVE_INTERVAL_MS = 30_000;

// Server-side ping/pong keepalive: browsers (and some proxies) don't always
// surface a dead TCP connection as a 'close' event, which would leave a
// dead session in the bridge registry forever answering "connected" while
// silently dropping every call. Every 30s, ping connections that answered
// the previous ping; terminate ones that didn't.
// Exported for unit testing with a fake socket + fake timers.
export function startKeepalive(socket: WebSocket): void {
  let isAlive = true;
  socket.on("pong", () => {
    isAlive = true;
  });

  const interval = setInterval(() => {
    if (!isAlive) {
      clearInterval(interval);
      socket.terminate();
      return;
    }
    isAlive = false;
    socket.ping();
  }, KEEPALIVE_INTERVAL_MS);

  socket.on("close", () => {
    clearInterval(interval);
  });
}

// Re-checks a cookie tab's auth session on a timer (the bridge also checks
// before every routed call). Cleared when the socket closes; a tab the check
// evicts is closed by the bridge, which fires the same close event.
export function startSessionRevalidation(
  socket: WebSocket,
  intervalMs = SESSION_REVALIDATE_INTERVAL_MS,
): void {
  const interval = setInterval(() => void revalidateSession(socket), intervalMs);
  interval.unref?.();
  socket.on("close", () => clearInterval(interval));
}
