import Fastify, {
  type FastifyInstance,
  type FastifyServerOptions,
} from "fastify";
import type { Config } from "./config.js";
import { registerCors } from "./plugins/cors.js";
import { registerMultipart } from "./plugins/multipart.js";
import { chatRoutes } from "./routes/chat.js";
import { generateImageRoutes } from "./routes/generateImage.js";
import { mcpRoutes } from "./mcp/routes.js";
import {
  getHandshakePath,
  removeHandshakeFile,
  resolveMcpAuth,
  writeHandshakeFile,
  type HandshakeFileEntry,
} from "./mcp/autoToken.js";
import { modelsRoutes } from "./routes/models.js";
import { prototypeLinkRoutes } from "./routes/prototype-link.js";
import { showcaseRoutes } from "./routes/showcase.js";
import { uploadRoutes } from "./routes/upload.js";
import { createTraceStore, type TraceStore } from "./tracing/traceStore.js";
import type { ShowcaseStore } from "./showcase/store.js";

export interface BuildAppOptions {
  logger?: FastifyServerOptions["logger"];
  // Test seam: inject a fake trace store. `undefined` = create from config,
  // `null` = explicitly disabled.
  traceStore?: TraceStore | null;
  // Test seam: inject a fake showcase store. `undefined` = create from
  // config, `null` = explicitly disabled.
  showcaseStore?: ShowcaseStore | null;
  // Whether this buildApp() call is the one long-running dev server
  // instance allowed to publish/reuse/clean up the shared handshake file at
  // ~/.pen-editor/mcp.json. Defaults to false: every other caller (test
  // suites, one-off scripts, anything that spins up buildApp() for a short
  // ephemeral instance) must never touch the real file, even when it
  // otherwise ends up in auto-token mode. Only src/index.ts — the actual
  // `npm run dev` / `npm start` entrypoint — sets this to true. A global
  // test-setup homedir redirect (test/setup.ts) is a second, independent
  // layer against the same mistake — see mcp-auto-token-publish.test.ts for
  // why both are required.
  publishHandshake?: boolean;
}

// The MCP WS upgrade (GET /api/mcp/ws?token=...) carries the auth token in
// the query string. Fastify's default request logging (pino) logs req.url
// verbatim, which would put the secret in plaintext logs. This serializer
// masks any `token=...` query param on the logged url; only applied when we
// build the default logger (options.logger left unset) so explicit caller
// configs (including `logger: false` in tests) are untouched.
export function maskTokenInUrl(url: string): string {
  return url.replace(/token=[^&]+/, "token=[redacted]");
}

function buildDefaultLogger(): FastifyServerOptions["logger"] {
  return {
    serializers: {
      req(request: { method?: string; url?: string }) {
        return {
          method: request.method,
          url: request.url ? maskTokenInUrl(request.url) : request.url,
        };
      },
    },
  };
}

export async function buildApp(
  config: Config,
  options: BuildAppOptions = {},
): Promise<FastifyInstance> {
  const app = Fastify({
    logger: options.logger ?? buildDefaultLogger(),
    bodyLimit: 10 * 1024 * 1024, // 10 MB — base64 images can be 2-5 MB each
  });

  await registerCors(app, config);
  await registerMultipart(app);

  const traceStore =
    options.traceStore !== undefined
      ? options.traceStore
      : createTraceStore(config);
  if (traceStore) {
    app.addHook("onClose", async () => {
      await traceStore.close();
    });
  }
  await chatRoutes(app, config, traceStore);
  await modelsRoutes(app, config);
  await uploadRoutes(app, config);
  await generateImageRoutes(app, config);
  await prototypeLinkRoutes(app, config);
  const showcaseStore = await showcaseRoutes(app, config, options.showcaseStore);
  if (showcaseStore) {
    app.addHook("onClose", async () => {
      await showcaseStore.close();
    });
  }

  app.setErrorHandler((error, _request, reply) => {
    app.log.error(error);
    const statusCode =
      typeof error === "object" && error !== null && "statusCode" in error
        ? (error as { statusCode: number }).statusCode
        : 500;
    const message =
      error instanceof Error ? error.message : "Internal Server Error";
    reply.status(statusCode).send({ error: message });
  });

  // Registered after setErrorHandler: @fastify/websocket (used by mcpRoutes)
  // decorates the root instance and, if registered first, causes routes
  // registered earlier on this instance to fall back to Fastify's default
  // {statusCode, error, message} error shape instead of ours — verified via
  // test/upload-route.test.ts's thrown-Error path (see mcp-server task 6
  // report for the repro).
  const mcpAuth = await resolveMcpAuth(config, {
    reuseFromHandshake: options.publishHandshake === true,
  });
  await mcpRoutes(app, config, mcpAuth);

  if (mcpAuth.autoGenerated && options.publishHandshake) {
    // No manual token wiring for local dev: MCP_AUTH_TOKEN unset means we
    // generated (or reused, see resolveMcpAuth) a token above and gated
    // /api/mcp* to loopback callers only (src/mcp/routes.ts). Publish it to
    // the shared handshake file other local tools (the editor, an MCP
    // client) read to connect with zero configuration — only once the real
    // listening port is known, hence the onListen hook rather than doing
    // this inline here.
    app.log.info(
      "[mcp] MCP_AUTH_TOKEN not set — enabling /api/mcp* with an auto-generated token, restricted to 127.0.0.1.",
    );
    // Captured so onClose can (a) wait for the write to actually land before
    // deciding whether to remove anything — a process that listens and
    // closes quickly could otherwise run removeHandshakeFile before the
    // write's rename lands, leaving exactly the stale file the cleanup
    // exists to prevent — and (b) verify the file it's about to delete is
    // still the one this process itself wrote (see removeHandshakeFile).
    let handshakeEntry: HandshakeFileEntry | undefined;
    let writeDone: Promise<void> = Promise.resolve();
    app.addHook("onListen", async () => {
      const address = app.server.address();
      const port = typeof address === "object" && address !== null ? address.port : config.PORT;
      // Non-null: this branch only runs when mcpAuth.autoGenerated is true,
      // which resolveMcpAuth only ever returns alongside a real token.
      handshakeEntry = { url: `http://127.0.0.1:${port}/api/mcp`, token: mcpAuth.token!, port };
      writeDone = writeHandshakeFile(handshakeEntry, app.log);
      await writeDone;
    });
    app.addHook("onClose", async () => {
      await writeDone;
      if (handshakeEntry) {
        await removeHandshakeFile(handshakeEntry, app.log);
      }
    });
  } else if (mcpAuth.autoGenerated) {
    app.log.debug(
      `[mcp] auto-token mode active but this instance does not publish/read the shared handshake file (not the long-running dev server).`,
    );
  } else {
    app.log.debug(`[mcp] MCP_AUTH_TOKEN set explicitly — not writing ${getHandshakePath()}.`);
  }

  return app;
}
