// Curated pool of mobile-app domains the showcase generator picks from. Kept
// broad (consumer + prosumer + niche) so a long run doesn't feel repetitive.
// Worth keeping comfortably larger than the `recentThemes(10)` exclusion
// window: once the pool shrinks toward 10, `pickTheme` has almost nothing left
// to choose from and the gallery starts cycling the same domains.
export const SHOWCASE_THEMES: string[] = [
  "fitness tracker",
  "mobile banking",
  "recipe app",
  "car sharing",
  "meditation and sleep",
  "houseplant care",
  "movie tickets",
  "habit tracker",
  "food delivery",
  "travel planner",
  "ebook reader",
  "expense tracker",
  "weather forecast",
  "notes and to-do lists",
  "language learning",
  "music player",
  "sleep tracker",
  "secondhand marketplace",
  "yoga app",
  "water intake tracker",
  "restaurant table booking",
  "cycling app",
  "mood tracker",
  "ride hailing",
  "pet care app",
  "medication tracker",
  "scooter sharing",
  "wedding planner",
  "TV show and movie tracker",
  "public transit navigation",
  "parking finder",
  "flight tracker",
  "hotel booking",
  "concert and event tickets",
  "podcast player",
  "budgeting and savings goals",
  "crypto portfolio tracker",
  "stock investing app",
  "insurance claims",
  "package delivery tracking",
  "grocery shopping list",
  "meal planning and macros",
  "running coach",
  "climbing gym logbook",
  "surf and tide forecast",
  "hiking trail guide",
  "stargazing guide",
  "birdwatching log",
  "smart home control",
  "car maintenance log",
  "EV charging map",
  "dog walking service",
  "baby tracker",
  "period and cycle tracking",
  "journaling and therapy companion",
  "local events discovery",
  "museum audio guide",
  "flashcards and spaced repetition",
  "chores and allowance for families",
  "roommate expense splitting",
  "apartment rental search",
  "job search",
  "freelance gig marketplace",
  "salon and barber booking",
  "telemedicine consultations",
  "fitness class booking",
  "sports scores and league tracker",
  "fantasy sports",
  "board game score keeper",
  "trivia quiz game",
  "photo journal",
  "wine tasting notes",
  "coffee brewing guide",
  "cocktail recipes",
  "restaurant discovery and reviews",
  "loyalty cards and rewards wallet",
  "charity fundraising",
  "dating app",
  "guitar practice and tuner",
  "sobriety tracker",
  "travel phrasebook and translation",
  "campsite booking",
  "ski resort app",
  "voice memos and transcription",
  "focus timer",
  "screen time and digital wellbeing",
  "password manager",
  "warranty and receipts organizer",
];

// Curated pool of desktop web-app domains — the productivity/prosumer/B2B
// software people actually run in a browser window, as distinct from
// `SHOWCASE_THEMES`'s consumer mobile-app pool. Kept separate rather than
// filtered from one shared list because very few of these translate to a
// phone screen (nobody wants a DAW or an infra dashboard on a 390px-wide
// canvas), and vice versa.
export const DESKTOP_THEMES: string[] = [
  "analytics dashboard",
  "CRM",
  "billing and subscriptions admin",
  "email client",
  "project planner",
  "audio workstation (DAW)",
  "code editor / IDE",
  "infrastructure monitoring dashboard",
  "CMS",
  "HR portal",
  "applicant tracking system",
  "customer support helpdesk",
  "invoicing and accounting",
  "design system documentation site",
  "API developer portal",
  "kanban project board",
  "video editing suite",
  "spreadsheet / data grid app",
  "server / database admin panel",
  "e-commerce back office",
  "marketing campaign builder",
  "knowledge base / wiki",
  "team calendar and scheduling",
  "warehouse and inventory management",
  "feature flags and A/B testing console",
  "CI/CD pipeline dashboard",
  "error tracking and observability",
  "log search console",
  "cloud cost management",
  "data pipeline orchestrator",
  "BI report builder",
  "SQL notebook",
  "ML experiment tracker",
  "LLM prompt playground",
  "data labeling and annotation tool",
  "localization and translation management",
  "podcast recording studio",
  "photo library and RAW editor",
  "3D modeling / CAD",
  "whiteboard and diagramming tool",
  "presentation editor",
  "collaborative document editor",
  "PDF review and e-signature",
  "contract lifecycle management",
  "clinic practice management (EHR)",
  "school learning management system",
  "hotel property management system",
  "restaurant point-of-sale back office",
  "fleet and logistics dispatch",
  "field service scheduling",
  "manufacturing production dashboard",
  "energy grid monitoring",
  "trading terminal",
  "insurance underwriting workbench",
  "payroll and benefits admin",
  "procurement and vendor management",
  "IT asset and device inventory",
  "identity and access management console",
  "security operations center console",
  "social media scheduling suite",
  "community moderation console",
  "customer feedback and roadmap portal",
  "code review tool",
  "API testing client",
  "live broadcast control room",
  "DJ and music library software",
  "nonprofit donor management",
];

// Picks a random theme from `themes`, avoiding anything in `recent` when
// possible. If every theme is "recent" (small pool, long history), the
// exclusion is dropped rather than throwing or looping forever — otherwise a
// run with a short theme list would eventually have nothing left to pick.
export function pickTheme(
  themes: string[],
  recent: string[],
  random: () => number,
): string {
  if (themes.length === 0) {
    throw new Error("pickTheme: themes list must not be empty");
  }

  const recentSet = new Set(recent);
  const candidates = themes.filter((t) => !recentSet.has(t));
  const pool = candidates.length > 0 ? candidates : themes;

  const index = Math.floor(random() * pool.length);
  // Guard against a random() implementation returning exactly 1.
  return pool[Math.min(index, pool.length - 1)];
}
